#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Orion.Xam.Android.SearchBox.Sample.Resource", IsApplication=true)]

namespace Orion.Xam.Android.SearchBox.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Orion.Xam.Android.SearchBox.Resource.Animation.AnimDown = global::Orion.Xam.Android.SearchBox.Sample.Resource.Animation.AnimDown;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.ambientEnabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.ambientEnabled;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.cameraBearing = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.cameraBearing;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.cameraTargetLat = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.cameraTargetLat;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.cameraTargetLng = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.cameraTargetLng;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.cameraTilt = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.cameraTilt;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.cameraZoom = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.cameraZoom;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.circleCrop = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.circleCrop;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.drawableRight = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.drawableRight;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.imageAspectRatio = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.imageAspectRatio;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.imageAspectRatioAdjust = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.imageAspectRatioAdjust;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.liteMode = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.liteMode;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.mapType = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.mapType;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.mapsResults = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.mapsResults;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.placeholder = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.placeholder;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiCompass = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiCompass;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiMapToolbar = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiMapToolbar;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiRotateGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiRotateGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiScrollGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiScrollGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiTiltGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiTiltGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiZoomControls = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiZoomControls;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiZoomGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiZoomGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.useViewLifecycle = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.useViewLifecycle;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.zOrderOnTop = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.zOrderOnTop;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_action_bar_splitter = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_action_bar_splitter;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_signin_btn_dark_text_default = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_signin_btn_dark_text_default;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_signin_btn_dark_text_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_signin_btn_dark_text_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_signin_btn_dark_text_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_signin_btn_dark_text_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_signin_btn_dark_text_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_signin_btn_dark_text_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_signin_btn_default_background = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_signin_btn_default_background;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_signin_btn_light_text_default = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_signin_btn_light_text_default;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_signin_btn_light_text_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_signin_btn_light_text_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_signin_btn_light_text_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_signin_btn_light_text_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_signin_btn_light_text_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_signin_btn_light_text_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_signin_btn_text_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_signin_btn_text_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_signin_btn_text_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_signin_btn_text_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_full_open_on_phone = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_full_open_on_phone;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_ic_googleplayservices = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_ic_googleplayservices;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_icon_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_icon_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_icon_disabled_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_icon_disabled_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_icon_disabled_focus_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_icon_disabled_focus_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_icon_disabled_focus_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_icon_disabled_focus_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_icon_disabled_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_icon_disabled_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_icon_focus_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_icon_focus_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_icon_focus_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_icon_focus_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_icon_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_icon_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_icon_normal_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_icon_normal_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_icon_normal_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_icon_normal_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_icon_pressed_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_icon_pressed_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_icon_pressed_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_icon_pressed_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_text_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_text_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_text_disabled_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_text_disabled_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_text_disabled_focus_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_text_disabled_focus_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_text_disabled_focus_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_text_disabled_focus_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_text_disabled_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_text_disabled_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_text_focus_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_text_focus_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_text_focus_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_text_focus_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_text_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_text_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_text_normal_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_text_normal_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_text_normal_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_text_normal_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_text_pressed_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_text_pressed_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_signin_btn_text_pressed_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_signin_btn_text_pressed_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.ic_action_mic = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.ic_action_mic;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.ic_clear = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.ic_clear;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.ic_more_vert_black_24dp = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.ic_more_vert_black_24dp;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.powered_by_google_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.powered_by_google_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.powered_by_google_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.powered_by_google_light;
			global::Orion.Xam.Android.SearchBox.Resource.Id.adjust_height = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.adjust_height;
			global::Orion.Xam.Android.SearchBox.Resource.Id.adjust_width = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.adjust_width;
			global::Orion.Xam.Android.SearchBox.Resource.Id.hybrid = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.hybrid;
			global::Orion.Xam.Android.SearchBox.Resource.Id.none = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.none;
			global::Orion.Xam.Android.SearchBox.Resource.Id.normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.normal;
			global::Orion.Xam.Android.SearchBox.Resource.Id.satellite = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.satellite;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_border = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_border;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_clear = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_clear;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_icon = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_icon;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_list_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_list_button;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_list_results = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_list_results;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_mic = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_mic;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_overflow = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_overflow;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_placeholder = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_placeholder;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_root = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_root;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_root_list_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_root_list_button;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_search = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_search;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_searchArea = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_searchArea;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_title;
			global::Orion.Xam.Android.SearchBox.Resource.Id.terrain = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.terrain;
			global::Orion.Xam.Android.SearchBox.Resource.Id.up = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.up;
			global::Orion.Xam.Android.SearchBox.Resource.Integer.google_play_services_version = global::Orion.Xam.Android.SearchBox.Sample.Resource.Integer.google_play_services_version;
			global::Orion.Xam.Android.SearchBox.Resource.Layout.search_box = global::Orion.Xam.Android.SearchBox.Sample.Resource.Layout.search_box;
			global::Orion.Xam.Android.SearchBox.Resource.Layout.SearchOption = global::Orion.Xam.Android.SearchBox.Sample.Resource.Layout.SearchOption;
			global::Orion.Xam.Android.SearchBox.Resource.String.ApplicationName = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.ApplicationName;
			global::Orion.Xam.Android.SearchBox.Resource.String.Hello = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.Hello;
			global::Orion.Xam.Android.SearchBox.Resource.String.auth_google_play_services_client_facebook_display_name = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.auth_google_play_services_client_facebook_display_name;
			global::Orion.Xam.Android.SearchBox.Resource.String.auth_google_play_services_client_google_display_name = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.auth_google_play_services_client_google_display_name;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_android_wear_notification_needs_update_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_android_wear_notification_needs_update_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_android_wear_update_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_android_wear_update_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_android_wear_update_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_android_wear_update_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_api_unavailable_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_api_unavailable_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_enable_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_enable_button;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_enable_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_enable_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_enable_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_enable_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_error_notification_requested_by_msg = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_error_notification_requested_by_msg;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_install_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_install_button;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_install_text_phone = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_install_text_phone;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_install_text_tablet = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_install_text_tablet;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_install_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_install_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_invalid_account_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_invalid_account_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_invalid_account_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_invalid_account_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_needs_enabling_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_needs_enabling_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_network_error_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_network_error_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_network_error_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_network_error_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_notification_needs_update_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_notification_needs_update_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_notification_ticker = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_notification_ticker;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_sign_in_failed_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_sign_in_failed_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_sign_in_failed_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_sign_in_failed_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_unknown_issue = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_unknown_issue;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_unsupported_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_unsupported_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_unsupported_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_unsupported_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_update_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_update_button;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_update_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_update_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_update_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_update_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_updating_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_updating_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_updating_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_updating_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_open_on_phone = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_open_on_phone;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_signin_button_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_signin_button_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_signin_button_text_long = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_signin_button_text_long;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.LoadingImageView = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.LoadingImageView;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.LoadingImageView_circleCrop = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.LoadingImageView_circleCrop;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.LoadingImageView_imageAspectRatio = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.LoadingImageView_imageAspectRatio;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_ambientEnabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_ambientEnabled;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_cameraBearing = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_cameraBearing;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_cameraTargetLat = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_cameraTargetLat;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_cameraTargetLng = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_cameraTargetLng;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_cameraTilt = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_cameraTilt;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_cameraZoom = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_cameraZoom;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_liteMode = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_liteMode;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_mapType = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_mapType;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiCompass = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiCompass;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiMapToolbar = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiMapToolbar;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiRotateGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiRotateGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiScrollGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiScrollGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiTiltGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiTiltGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiZoomControls = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiZoomControls;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiZoomGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiZoomGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_useViewLifecycle = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_useViewLifecycle;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_zOrderOnTop = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_zOrderOnTop;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SearchBoxView = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SearchBoxView;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SearchBoxView_drawableRight = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SearchBoxView_drawableRight;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SearchBoxView_mapsResults = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SearchBoxView_mapsResults;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SearchBoxView_placeholder = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SearchBoxView_placeholder;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int AnimDown = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f010016
			public const int drawableRight = 2130771990;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010015
			public const int mapsResults = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int placeholder = 2130771988;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060009
			public const int common_action_bar_splitter = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int common_signin_btn_dark_text_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_signin_btn_dark_text_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_signin_btn_dark_text_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_signin_btn_dark_text_pressed = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int common_signin_btn_default_background = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int common_signin_btn_light_text_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_signin_btn_light_text_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_signin_btn_light_text_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_signin_btn_light_text_pressed = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int common_signin_btn_text_dark = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_signin_btn_text_light = 2131099659;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_ic_googleplayservices = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_pressed_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_action_mic = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_clear = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_more_vert_black_24dp = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Icon = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int powered_by_google_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int powered_by_google_light = 2130837535;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public const int adjust_height = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int adjust_width = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int hybrid = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int none = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int normal = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int satellite = 2131230723;
			
			// aapt resource value: 0x7f080015
			public const int sb_border = 2131230741;
			
			// aapt resource value: 0x7f080010
			public const int sb_clear = 2131230736;
			
			// aapt resource value: 0x7f080012
			public const int sb_icon = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int sb_list_button = 2131230737;
			
			// aapt resource value: 0x7f080009
			public const int sb_list_results = 2131230729;
			
			// aapt resource value: 0x7f08000d
			public const int sb_mic = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int sb_overflow = 2131230735;
			
			// aapt resource value: 0x7f08000b
			public const int sb_placeholder = 2131230731;
			
			// aapt resource value: 0x7f080008
			public const int sb_root = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int sb_root_list_button = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int sb_search = 2131230734;
			
			// aapt resource value: 0x7f08000a
			public const int sb_searchArea = 2131230730;
			
			// aapt resource value: 0x7f080013
			public const int sb_title = 2131230739;
			
			// aapt resource value: 0x7f080007
			public const int searchbox = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int terrain = 2131230724;
			
			// aapt resource value: 0x7f080014
			public const int up = 2131230740;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int search_box = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SearchOption = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050023
			public const int ApplicationName = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int Hello = 2131034146;
			
			// aapt resource value: 0x7f050003
			public const int auth_google_play_services_client_facebook_display_name = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int auth_google_play_services_client_google_display_name = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int common_android_wear_notification_needs_update_text = 2131034118;
			
			// aapt resource value: 0x7f050013
			public const int common_android_wear_update_text = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int common_android_wear_update_title = 2131034129;
			
			// aapt resource value: 0x7f05001f
			public const int common_google_play_services_api_unavailable_text = 2131034143;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_play_services_enable_button = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_enable_text = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_enable_title = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_error_notification_requested_by_msg = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_install_button = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_install_text_phone = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_install_text_tablet = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_install_title = 2131034121;
			
			// aapt resource value: 0x7f050019
			public const int common_google_play_services_invalid_account_text = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int common_google_play_services_invalid_account_title = 2131034136;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_needs_enabling_title = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int common_google_play_services_network_error_text = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int common_google_play_services_network_error_title = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_notification_needs_update_title = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_notification_ticker = 2131034116;
			
			// aapt resource value: 0x7f050021
			public const int common_google_play_services_sign_in_failed_text = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int common_google_play_services_sign_in_failed_title = 2131034144;
			
			// aapt resource value: 0x7f05001a
			public const int common_google_play_services_unknown_issue = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int common_google_play_services_unsupported_text = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int common_google_play_services_unsupported_title = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int common_google_play_services_update_button = 2131034141;
			
			// aapt resource value: 0x7f050012
			public const int common_google_play_services_update_text = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_update_title = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int common_google_play_services_updating_text = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int common_google_play_services_updating_title = 2131034132;
			
			// aapt resource value: 0x7f05001e
			public const int common_open_on_phone = 2131034142;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_button_text = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_button_text_long = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SearchBoxView = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 2
			public const int SearchBoxView_drawableRight = 2;
			
			// aapt resource value: 1
			public const int SearchBoxView_mapsResults = 1;
			
			// aapt resource value: 0
			public const int SearchBoxView_placeholder = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
