#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Orion.Xam.Android.SearchBox.Sample.Resource", IsApplication=true)]

namespace Orion.Xam.Android.SearchBox.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Orion.Xam.Android.SearchBox.Resource.Animation.AnimDown = global::Orion.Xam.Android.SearchBox.Sample.Resource.Animation.AnimDown;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.ambientEnabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.ambientEnabled;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.buttonSize = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.buttonSize;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.cameraBearing = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.cameraBearing;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.cameraTargetLat = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.cameraTargetLat;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.cameraTargetLng = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.cameraTargetLng;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.cameraTilt = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.cameraTilt;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.cameraZoom = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.cameraZoom;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.circleCrop = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.circleCrop;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.colorScheme = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.colorScheme;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.drawableRight = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.drawableRight;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.imageAspectRatio = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.imageAspectRatio;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.imageAspectRatioAdjust = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.imageAspectRatioAdjust;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.liteMode = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.liteMode;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.mapType = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.mapType;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.mapsResults = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.mapsResults;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.placeholder = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.placeholder;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.scopeUris = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.scopeUris;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiCompass = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiCompass;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiMapToolbar = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiMapToolbar;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiRotateGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiRotateGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiScrollGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiScrollGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiTiltGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiTiltGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiZoomControls = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiZoomControls;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiZoomGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiZoomGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.useViewLifecycle = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.useViewLifecycle;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.zOrderOnTop = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.zOrderOnTop;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_action_bar_splitter = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_action_bar_splitter;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_dark_default = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_dark_default;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_dark_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_dark_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_dark_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_dark_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_dark_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_dark_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_light;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_light_default = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_light_default;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_light_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_light_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_light_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_light_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_light_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_light_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_dark_default = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_dark_default;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_dark_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_dark_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_dark_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_dark_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_dark_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_dark_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_light;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_light_default = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_light_default;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_light_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_light_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_light_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_light_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_light_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_light_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Color.place_autocomplete_prediction_primary_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.place_autocomplete_prediction_primary_text;
			global::Orion.Xam.Android.SearchBox.Resource.Color.place_autocomplete_prediction_primary_text_highlight = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.place_autocomplete_prediction_primary_text_highlight;
			global::Orion.Xam.Android.SearchBox.Resource.Color.place_autocomplete_prediction_secondary_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.place_autocomplete_prediction_secondary_text;
			global::Orion.Xam.Android.SearchBox.Resource.Color.place_autocomplete_search_hint = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.place_autocomplete_search_hint;
			global::Orion.Xam.Android.SearchBox.Resource.Color.place_autocomplete_search_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.place_autocomplete_search_text;
			global::Orion.Xam.Android.SearchBox.Resource.Color.place_autocomplete_separator = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.place_autocomplete_separator;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_button_padding = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_button_padding;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_powered_by_google_height = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_powered_by_google_height;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_powered_by_google_start = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_powered_by_google_start;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_prediction_height = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_prediction_height;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_prediction_horizontal_margin = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_prediction_horizontal_margin;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_prediction_primary_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_prediction_primary_text;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_prediction_secondary_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_prediction_secondary_text;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_progress_horizontal_margin = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_progress_horizontal_margin;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_progress_size = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_progress_size;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_separator_start = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_separator_start;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_full_open_on_phone = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_full_open_on_phone;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_dark_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_dark_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_dark_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_dark_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_dark_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_dark_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_dark_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_dark_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_light_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_light_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_light_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_light_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_light_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_light_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_light_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_light_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_dark_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_dark_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_dark_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_dark_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_dark_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_dark_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_dark_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_dark_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_light_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_light_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_light_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_light_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_light_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_light_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_light_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_light_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_ic_googleplayservices = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_ic_googleplayservices;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_dark_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_dark_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_dark_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_dark_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_dark_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_dark_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_dark_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_dark_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_light_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_light_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_light_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_light_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_light_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_light_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_light_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_light_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_dark_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_dark_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_dark_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_dark_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_dark_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_dark_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_dark_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_dark_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_light_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_light_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_light_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_light_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_light_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_light_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_light_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_light_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.ic_action_mic = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.ic_action_mic;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.ic_clear = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.ic_clear;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.ic_more_vert_black_24dp = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.ic_more_vert_black_24dp;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.places_ic_clear = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.places_ic_clear;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.places_ic_search = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.places_ic_search;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.powered_by_google_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.powered_by_google_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.powered_by_google_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.powered_by_google_light;
			global::Orion.Xam.Android.SearchBox.Resource.Id.adjust_height = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.adjust_height;
			global::Orion.Xam.Android.SearchBox.Resource.Id.adjust_width = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.adjust_width;
			global::Orion.Xam.Android.SearchBox.Resource.Id.auto = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.auto;
			global::Orion.Xam.Android.SearchBox.Resource.Id.dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.dark;
			global::Orion.Xam.Android.SearchBox.Resource.Id.hybrid = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.hybrid;
			global::Orion.Xam.Android.SearchBox.Resource.Id.icon_only = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.icon_only;
			global::Orion.Xam.Android.SearchBox.Resource.Id.light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.light;
			global::Orion.Xam.Android.SearchBox.Resource.Id.none = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.none;
			global::Orion.Xam.Android.SearchBox.Resource.Id.normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.normal;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_clear_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_clear_button;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_powered_by_google = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_powered_by_google;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_prediction_primary_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_prediction_primary_text;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_prediction_secondary_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_prediction_secondary_text;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_progress = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_progress;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_search_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_search_button;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_search_input = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_search_input;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_separator = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_separator;
			global::Orion.Xam.Android.SearchBox.Resource.Id.satellite = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.satellite;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_border = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_border;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_clear = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_clear;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_icon = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_icon;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_list_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_list_button;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_list_results = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_list_results;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_mic = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_mic;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_overflow = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_overflow;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_placeholder = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_placeholder;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_root = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_root;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_root_list_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_root_list_button;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_search = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_search;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_searchArea = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_searchArea;
			global::Orion.Xam.Android.SearchBox.Resource.Id.sb_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.sb_title;
			global::Orion.Xam.Android.SearchBox.Resource.Id.standard = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.standard;
			global::Orion.Xam.Android.SearchBox.Resource.Id.terrain = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.terrain;
			global::Orion.Xam.Android.SearchBox.Resource.Id.up = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.up;
			global::Orion.Xam.Android.SearchBox.Resource.Id.wide = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.wide;
			global::Orion.Xam.Android.SearchBox.Resource.Integer.google_play_services_version = global::Orion.Xam.Android.SearchBox.Sample.Resource.Integer.google_play_services_version;
			global::Orion.Xam.Android.SearchBox.Resource.Layout.place_autocomplete_fragment = global::Orion.Xam.Android.SearchBox.Sample.Resource.Layout.place_autocomplete_fragment;
			global::Orion.Xam.Android.SearchBox.Resource.Layout.place_autocomplete_item_powered_by_google = global::Orion.Xam.Android.SearchBox.Sample.Resource.Layout.place_autocomplete_item_powered_by_google;
			global::Orion.Xam.Android.SearchBox.Resource.Layout.place_autocomplete_item_prediction = global::Orion.Xam.Android.SearchBox.Sample.Resource.Layout.place_autocomplete_item_prediction;
			global::Orion.Xam.Android.SearchBox.Resource.Layout.place_autocomplete_progress = global::Orion.Xam.Android.SearchBox.Sample.Resource.Layout.place_autocomplete_progress;
			global::Orion.Xam.Android.SearchBox.Resource.Layout.search_box = global::Orion.Xam.Android.SearchBox.Sample.Resource.Layout.search_box;
			global::Orion.Xam.Android.SearchBox.Resource.Layout.SearchOption = global::Orion.Xam.Android.SearchBox.Sample.Resource.Layout.SearchOption;
			global::Orion.Xam.Android.SearchBox.Resource.String.ApplicationName = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.ApplicationName;
			global::Orion.Xam.Android.SearchBox.Resource.String.Hello = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.Hello;
			global::Orion.Xam.Android.SearchBox.Resource.String.auth_google_play_services_client_facebook_display_name = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.auth_google_play_services_client_facebook_display_name;
			global::Orion.Xam.Android.SearchBox.Resource.String.auth_google_play_services_client_google_display_name = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.auth_google_play_services_client_google_display_name;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_api_unavailable_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_api_unavailable_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_enable_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_enable_button;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_enable_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_enable_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_enable_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_enable_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_install_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_install_button;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_install_text_phone = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_install_text_phone;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_install_text_tablet = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_install_text_tablet;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_install_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_install_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_invalid_account_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_invalid_account_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_invalid_account_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_invalid_account_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_network_error_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_network_error_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_network_error_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_network_error_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_notification_ticker = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_notification_ticker;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_restricted_profile_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_restricted_profile_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_restricted_profile_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_restricted_profile_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_sign_in_failed_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_sign_in_failed_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_sign_in_failed_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_sign_in_failed_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_unknown_issue = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_unknown_issue;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_unsupported_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_unsupported_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_unsupported_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_unsupported_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_update_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_update_button;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_update_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_update_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_update_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_update_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_updating_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_updating_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_updating_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_updating_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_wear_update_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_wear_update_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_open_on_phone = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_open_on_phone;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_signin_button_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_signin_button_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_signin_button_text_long = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_signin_button_text_long;
			global::Orion.Xam.Android.SearchBox.Resource.String.place_autocomplete_clear_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.place_autocomplete_clear_button;
			global::Orion.Xam.Android.SearchBox.Resource.String.place_autocomplete_search_hint = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.place_autocomplete_search_hint;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.LoadingImageView = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.LoadingImageView;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.LoadingImageView_circleCrop = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.LoadingImageView_circleCrop;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.LoadingImageView_imageAspectRatio = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.LoadingImageView_imageAspectRatio;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_ambientEnabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_ambientEnabled;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_cameraBearing = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_cameraBearing;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_cameraTargetLat = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_cameraTargetLat;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_cameraTargetLng = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_cameraTargetLng;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_cameraTilt = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_cameraTilt;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_cameraZoom = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_cameraZoom;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_liteMode = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_liteMode;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_mapType = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_mapType;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiCompass = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiCompass;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiMapToolbar = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiMapToolbar;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiRotateGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiRotateGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiScrollGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiScrollGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiTiltGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiTiltGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiZoomControls = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiZoomControls;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiZoomGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiZoomGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_useViewLifecycle = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_useViewLifecycle;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_zOrderOnTop = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_zOrderOnTop;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SearchBoxView = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SearchBoxView;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SearchBoxView_drawableRight = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SearchBoxView_drawableRight;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SearchBoxView_mapsResults = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SearchBoxView_mapsResults;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SearchBoxView_placeholder = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SearchBoxView_placeholder;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SignInButton = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SignInButton;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SignInButton_buttonSize = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SignInButton_buttonSize;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SignInButton_colorScheme = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SignInButton_colorScheme;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SignInButton_scopeUris = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SignInButton_scopeUris;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int AnimDown = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int drawableRight = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int mapsResults = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int placeholder = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_mic = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_clear = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_more_vert_black_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000e
			public const int sb_border = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int sb_clear = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int sb_icon = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int sb_list_button = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int sb_list_results = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int sb_mic = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int sb_overflow = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int sb_placeholder = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int sb_root = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int sb_root_list_button = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int sb_search = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int sb_searchArea = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int sb_title = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int searchbox = 2131099648;
			
			// aapt resource value: 0x7f06000d
			public const int up = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int search_box = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SearchOption = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SearchBoxView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int SearchBoxView_drawableRight = 2;
			
			// aapt resource value: 1
			public const int SearchBoxView_mapsResults = 1;
			
			// aapt resource value: 0
			public const int SearchBoxView_placeholder = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
