#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Orion.Xam.Android.SearchBox.Sample.Resource", IsApplication=true)]

namespace Orion.Xam.Android.SearchBox.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Orion.Xam.Android.SearchBox.Resource.Animation.AnimDown = global::Orion.Xam.Android.SearchBox.Sample.Resource.Animation.AnimDown;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.ambientEnabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.ambientEnabled;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.buttonSize = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.buttonSize;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.cameraBearing = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.cameraBearing;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.cameraTargetLat = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.cameraTargetLat;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.cameraTargetLng = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.cameraTargetLng;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.cameraTilt = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.cameraTilt;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.cameraZoom = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.cameraZoom;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.circleCrop = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.circleCrop;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.colorScheme = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.colorScheme;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.drawableRight = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.drawableRight;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.imageAspectRatio = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.imageAspectRatio;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.imageAspectRatioAdjust = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.imageAspectRatioAdjust;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.liteMode = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.liteMode;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.mapType = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.mapType;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.mapsResults = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.mapsResults;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.placeholder = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.placeholder;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.scopeUris = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.scopeUris;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiCompass = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiCompass;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiMapToolbar = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiMapToolbar;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiRotateGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiRotateGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiScrollGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiScrollGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiTiltGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiTiltGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiZoomControls = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiZoomControls;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.uiZoomGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.uiZoomGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.useViewLifecycle = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.useViewLifecycle;
			global::Orion.Xam.Android.SearchBox.Resource.Attribute.zOrderOnTop = global::Orion.Xam.Android.SearchBox.Sample.Resource.Attribute.zOrderOnTop;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_action_bar_splitter = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_action_bar_splitter;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_dark_default = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_dark_default;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_dark_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_dark_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_dark_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_dark_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_dark_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_dark_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_light;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_light_default = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_light_default;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_light_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_light_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_light_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_light_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_google_signin_btn_text_light_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_google_signin_btn_text_light_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_dark_default = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_dark_default;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_dark_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_dark_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_dark_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_dark_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_dark_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_dark_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_light;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_light_default = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_light_default;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_light_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_light_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_light_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_light_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Color.common_plus_signin_btn_text_light_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.common_plus_signin_btn_text_light_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Color.place_autocomplete_prediction_primary_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.place_autocomplete_prediction_primary_text;
			global::Orion.Xam.Android.SearchBox.Resource.Color.place_autocomplete_prediction_primary_text_highlight = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.place_autocomplete_prediction_primary_text_highlight;
			global::Orion.Xam.Android.SearchBox.Resource.Color.place_autocomplete_prediction_secondary_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.place_autocomplete_prediction_secondary_text;
			global::Orion.Xam.Android.SearchBox.Resource.Color.place_autocomplete_search_hint = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.place_autocomplete_search_hint;
			global::Orion.Xam.Android.SearchBox.Resource.Color.place_autocomplete_search_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.place_autocomplete_search_text;
			global::Orion.Xam.Android.SearchBox.Resource.Color.place_autocomplete_separator = global::Orion.Xam.Android.SearchBox.Sample.Resource.Color.place_autocomplete_separator;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_button_padding = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_button_padding;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_powered_by_google_height = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_powered_by_google_height;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_powered_by_google_start = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_powered_by_google_start;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_prediction_height = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_prediction_height;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_prediction_horizontal_margin = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_prediction_horizontal_margin;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_prediction_primary_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_prediction_primary_text;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_prediction_secondary_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_prediction_secondary_text;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_progress_horizontal_margin = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_progress_horizontal_margin;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_progress_size = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_progress_size;
			global::Orion.Xam.Android.SearchBox.Resource.Dimension.place_autocomplete_separator_start = global::Orion.Xam.Android.SearchBox.Sample.Resource.Dimension.place_autocomplete_separator_start;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_full_open_on_phone = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_full_open_on_phone;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_dark_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_dark_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_dark_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_dark_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_dark_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_dark_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_dark_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_dark_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_light_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_light_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_light_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_light_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_light_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_light_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_icon_light_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_icon_light_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_dark_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_dark_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_dark_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_dark_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_dark_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_dark_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_dark_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_dark_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_light_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_light_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_light_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_light_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_light_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_light_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_google_signin_btn_text_light_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_google_signin_btn_text_light_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_ic_googleplayservices = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_ic_googleplayservices;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_dark_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_dark_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_dark_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_dark_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_dark_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_dark_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_dark_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_dark_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_light_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_light_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_light_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_light_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_light_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_light_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_icon_light_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_icon_light_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_dark_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_dark_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_dark_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_dark_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_dark_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_dark_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_dark_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_dark_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_light;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_light_disabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_light_disabled;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_light_focused = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_light_focused;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_light_normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_light_normal;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.common_plus_signin_btn_text_light_pressed = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.common_plus_signin_btn_text_light_pressed;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.ic_action_mic = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.ic_action_mic;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.ic_clear = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.ic_clear;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.ic_more_vert_black_24dp = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.ic_more_vert_black_24dp;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.places_ic_clear = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.places_ic_clear;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.places_ic_search = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.places_ic_search;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.powered_by_google_dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.powered_by_google_dark;
			global::Orion.Xam.Android.SearchBox.Resource.Drawable.powered_by_google_light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Drawable.powered_by_google_light;
			global::Orion.Xam.Android.SearchBox.Resource.Id.adjust_height = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.adjust_height;
			global::Orion.Xam.Android.SearchBox.Resource.Id.adjust_width = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.adjust_width;
			global::Orion.Xam.Android.SearchBox.Resource.Id.auto = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.auto;
			global::Orion.Xam.Android.SearchBox.Resource.Id.border = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.border;
			global::Orion.Xam.Android.SearchBox.Resource.Id.clear = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.clear;
			global::Orion.Xam.Android.SearchBox.Resource.Id.dark = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.dark;
			global::Orion.Xam.Android.SearchBox.Resource.Id.hybrid = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.hybrid;
			global::Orion.Xam.Android.SearchBox.Resource.Id.icon = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.icon;
			global::Orion.Xam.Android.SearchBox.Resource.Id.icon_only = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.icon_only;
			global::Orion.Xam.Android.SearchBox.Resource.Id.light = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.light;
			global::Orion.Xam.Android.SearchBox.Resource.Id.list_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.list_button;
			global::Orion.Xam.Android.SearchBox.Resource.Id.list_results = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.list_results;
			global::Orion.Xam.Android.SearchBox.Resource.Id.mic = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.mic;
			global::Orion.Xam.Android.SearchBox.Resource.Id.none = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.none;
			global::Orion.Xam.Android.SearchBox.Resource.Id.normal = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.normal;
			global::Orion.Xam.Android.SearchBox.Resource.Id.overflow = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.overflow;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_clear_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_clear_button;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_powered_by_google = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_powered_by_google;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_prediction_primary_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_prediction_primary_text;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_prediction_secondary_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_prediction_secondary_text;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_progress = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_progress;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_search_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_search_button;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_search_input = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_search_input;
			global::Orion.Xam.Android.SearchBox.Resource.Id.place_autocomplete_separator = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.place_autocomplete_separator;
			global::Orion.Xam.Android.SearchBox.Resource.Id.placeholder = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.placeholder;
			global::Orion.Xam.Android.SearchBox.Resource.Id.root = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.root;
			global::Orion.Xam.Android.SearchBox.Resource.Id.root_list_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.root_list_button;
			global::Orion.Xam.Android.SearchBox.Resource.Id.satellite = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.satellite;
			global::Orion.Xam.Android.SearchBox.Resource.Id.search = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.search;
			global::Orion.Xam.Android.SearchBox.Resource.Id.searchArea = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.searchArea;
			global::Orion.Xam.Android.SearchBox.Resource.Id.standard = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.standard;
			global::Orion.Xam.Android.SearchBox.Resource.Id.terrain = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.terrain;
			global::Orion.Xam.Android.SearchBox.Resource.Id.title = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.title;
			global::Orion.Xam.Android.SearchBox.Resource.Id.up = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.up;
			global::Orion.Xam.Android.SearchBox.Resource.Id.wide = global::Orion.Xam.Android.SearchBox.Sample.Resource.Id.wide;
			global::Orion.Xam.Android.SearchBox.Resource.Integer.google_play_services_version = global::Orion.Xam.Android.SearchBox.Sample.Resource.Integer.google_play_services_version;
			global::Orion.Xam.Android.SearchBox.Resource.Layout.place_autocomplete_fragment = global::Orion.Xam.Android.SearchBox.Sample.Resource.Layout.place_autocomplete_fragment;
			global::Orion.Xam.Android.SearchBox.Resource.Layout.place_autocomplete_item_powered_by_google = global::Orion.Xam.Android.SearchBox.Sample.Resource.Layout.place_autocomplete_item_powered_by_google;
			global::Orion.Xam.Android.SearchBox.Resource.Layout.place_autocomplete_item_prediction = global::Orion.Xam.Android.SearchBox.Sample.Resource.Layout.place_autocomplete_item_prediction;
			global::Orion.Xam.Android.SearchBox.Resource.Layout.place_autocomplete_progress = global::Orion.Xam.Android.SearchBox.Sample.Resource.Layout.place_autocomplete_progress;
			global::Orion.Xam.Android.SearchBox.Resource.Layout.SearchBox = global::Orion.Xam.Android.SearchBox.Sample.Resource.Layout.SearchBox;
			global::Orion.Xam.Android.SearchBox.Resource.Layout.SearchOption = global::Orion.Xam.Android.SearchBox.Sample.Resource.Layout.SearchOption;
			global::Orion.Xam.Android.SearchBox.Resource.String.ApplicationName = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.ApplicationName;
			global::Orion.Xam.Android.SearchBox.Resource.String.Hello = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.Hello;
			global::Orion.Xam.Android.SearchBox.Resource.String.auth_google_play_services_client_facebook_display_name = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.auth_google_play_services_client_facebook_display_name;
			global::Orion.Xam.Android.SearchBox.Resource.String.auth_google_play_services_client_google_display_name = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.auth_google_play_services_client_google_display_name;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_api_unavailable_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_api_unavailable_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_enable_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_enable_button;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_enable_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_enable_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_enable_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_enable_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_install_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_install_button;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_install_text_phone = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_install_text_phone;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_install_text_tablet = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_install_text_tablet;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_install_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_install_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_invalid_account_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_invalid_account_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_invalid_account_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_invalid_account_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_network_error_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_network_error_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_network_error_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_network_error_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_notification_ticker = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_notification_ticker;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_restricted_profile_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_restricted_profile_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_restricted_profile_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_restricted_profile_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_sign_in_failed_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_sign_in_failed_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_sign_in_failed_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_sign_in_failed_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_unknown_issue = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_unknown_issue;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_unsupported_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_unsupported_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_unsupported_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_unsupported_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_update_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_update_button;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_update_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_update_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_update_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_update_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_updating_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_updating_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_updating_title = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_updating_title;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_google_play_services_wear_update_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_google_play_services_wear_update_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_open_on_phone = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_open_on_phone;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_signin_button_text = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_signin_button_text;
			global::Orion.Xam.Android.SearchBox.Resource.String.common_signin_button_text_long = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.common_signin_button_text_long;
			global::Orion.Xam.Android.SearchBox.Resource.String.place_autocomplete_clear_button = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.place_autocomplete_clear_button;
			global::Orion.Xam.Android.SearchBox.Resource.String.place_autocomplete_search_hint = global::Orion.Xam.Android.SearchBox.Sample.Resource.String.place_autocomplete_search_hint;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.LoadingImageView = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.LoadingImageView;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.LoadingImageView_circleCrop = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.LoadingImageView_circleCrop;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.LoadingImageView_imageAspectRatio = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.LoadingImageView_imageAspectRatio;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_ambientEnabled = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_ambientEnabled;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_cameraBearing = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_cameraBearing;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_cameraTargetLat = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_cameraTargetLat;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_cameraTargetLng = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_cameraTargetLng;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_cameraTilt = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_cameraTilt;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_cameraZoom = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_cameraZoom;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_liteMode = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_liteMode;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_mapType = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_mapType;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiCompass = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiCompass;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiMapToolbar = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiMapToolbar;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiRotateGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiRotateGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiScrollGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiScrollGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiTiltGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiTiltGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiZoomControls = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiZoomControls;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_uiZoomGestures = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_uiZoomGestures;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_useViewLifecycle = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_useViewLifecycle;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.MapAttrs_zOrderOnTop = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.MapAttrs_zOrderOnTop;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SearchBoxView = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SearchBoxView;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SearchBoxView_drawableRight = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SearchBoxView_drawableRight;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SearchBoxView_mapsResults = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SearchBoxView_mapsResults;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SearchBoxView_placeholder = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SearchBoxView_placeholder;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SignInButton = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SignInButton;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SignInButton_buttonSize = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SignInButton_buttonSize;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SignInButton_colorScheme = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SignInButton_colorScheme;
			global::Orion.Xam.Android.SearchBox.Resource.Styleable.SignInButton_scopeUris = global::Orion.Xam.Android.SearchBox.Sample.Resource.Styleable.SignInButton_scopeUris;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int AnimDown = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010013
			public const int ambientEnabled = 2130771987;
			
			// aapt resource value: 0x7f010000
			public const int buttonSize = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int cameraBearing = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraTargetLat = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cameraTargetLng = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cameraTilt = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int cameraZoom = 2130771976;
			
			// aapt resource value: 0x7f010016
			public const int circleCrop = 2130771990;
			
			// aapt resource value: 0x7f010001
			public const int colorScheme = 2130771969;
			
			// aapt resource value: 0x7f010019
			public const int drawableRight = 2130771993;
			
			// aapt resource value: 0x7f010015
			public const int imageAspectRatio = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int imageAspectRatioAdjust = 2130771988;
			
			// aapt resource value: 0x7f010009
			public const int liteMode = 2130771977;
			
			// aapt resource value: 0x7f010003
			public const int mapType = 2130771971;
			
			// aapt resource value: 0x7f010018
			public const int mapsResults = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int placeholder = 2130771991;
			
			// aapt resource value: 0x7f010002
			public const int scopeUris = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public const int uiCompass = 2130771978;
			
			// aapt resource value: 0x7f010012
			public const int uiMapToolbar = 2130771986;
			
			// aapt resource value: 0x7f01000b
			public const int uiRotateGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiScrollGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int uiTiltGestures = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int uiZoomControls = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int uiZoomGestures = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int useViewLifecycle = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int zOrderOnTop = 2130771985;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int common_action_bar_splitter = 2131034120;
			
			// aapt resource value: 0x7f050017
			public const int common_google_signin_btn_text_dark = 2131034135;
			
			// aapt resource value: 0x7f050009
			public const int common_google_signin_btn_text_dark_default = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_signin_btn_text_dark_disabled = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_signin_btn_text_dark_focused = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_signin_btn_text_dark_pressed = 2131034122;
			
			// aapt resource value: 0x7f050018
			public const int common_google_signin_btn_text_light = 2131034136;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_signin_btn_text_light_default = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_signin_btn_text_light_disabled = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int common_google_signin_btn_text_light_focused = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_signin_btn_text_light_pressed = 2131034126;
			
			// aapt resource value: 0x7f050019
			public const int common_plus_signin_btn_text_dark = 2131034137;
			
			// aapt resource value: 0x7f050000
			public const int common_plus_signin_btn_text_dark_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_plus_signin_btn_text_dark_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_plus_signin_btn_text_dark_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_plus_signin_btn_text_dark_pressed = 2131034113;
			
			// aapt resource value: 0x7f05001a
			public const int common_plus_signin_btn_text_light = 2131034138;
			
			// aapt resource value: 0x7f050004
			public const int common_plus_signin_btn_text_light_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_plus_signin_btn_text_light_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_plus_signin_btn_text_light_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_plus_signin_btn_text_light_pressed = 2131034117;
			
			// aapt resource value: 0x7f050013
			public const int place_autocomplete_prediction_primary_text = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int place_autocomplete_prediction_primary_text_highlight = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int place_autocomplete_prediction_secondary_text = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int place_autocomplete_search_hint = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int place_autocomplete_search_text = 2131034129;
			
			// aapt resource value: 0x7f050016
			public const int place_autocomplete_separator = 2131034134;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int place_autocomplete_button_padding = 2131230720;
			
			// aapt resource value: 0x7f080008
			public const int place_autocomplete_powered_by_google_height = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int place_autocomplete_powered_by_google_start = 2131230729;
			
			// aapt resource value: 0x7f080003
			public const int place_autocomplete_prediction_height = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int place_autocomplete_prediction_horizontal_margin = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int place_autocomplete_prediction_primary_text = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int place_autocomplete_prediction_secondary_text = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int place_autocomplete_progress_horizontal_margin = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int place_autocomplete_progress_size = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int place_autocomplete_separator_start = 2131230727;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_ic_googleplayservices = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_plus_signin_btn_icon_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_plus_signin_btn_icon_dark_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_light_disabled = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_light_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_text_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_text_dark_disabled = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_text_dark_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_light_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_light_focused = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_action_mic = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_clear = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_more_vert_black_24dp = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Icon = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int places_ic_clear = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int places_ic_search = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int powered_by_google_dark = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int powered_by_google_light = 2130837553;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000b
			public const int adjust_height = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int adjust_width = 2131296268;
			
			// aapt resource value: 0x7f090003
			public const int auto = 2131296259;
			
			// aapt resource value: 0x7f090023
			public const int border = 2131296291;
			
			// aapt resource value: 0x7f09001e
			public const int clear = 2131296286;
			
			// aapt resource value: 0x7f090004
			public const int dark = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int hybrid = 2131296262;
			
			// aapt resource value: 0x7f090020
			public const int icon = 2131296288;
			
			// aapt resource value: 0x7f090000
			public const int icon_only = 2131296256;
			
			// aapt resource value: 0x7f090005
			public const int light = 2131296261;
			
			// aapt resource value: 0x7f09001f
			public const int list_button = 2131296287;
			
			// aapt resource value: 0x7f090017
			public const int list_results = 2131296279;
			
			// aapt resource value: 0x7f09001b
			public const int mic = 2131296283;
			
			// aapt resource value: 0x7f090007
			public const int none = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int normal = 2131296264;
			
			// aapt resource value: 0x7f09001d
			public const int overflow = 2131296285;
			
			// aapt resource value: 0x7f090010
			public const int place_autocomplete_clear_button = 2131296272;
			
			// aapt resource value: 0x7f090012
			public const int place_autocomplete_powered_by_google = 2131296274;
			
			// aapt resource value: 0x7f090014
			public const int place_autocomplete_prediction_primary_text = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int place_autocomplete_prediction_secondary_text = 2131296277;
			
			// aapt resource value: 0x7f090013
			public const int place_autocomplete_progress = 2131296275;
			
			// aapt resource value: 0x7f09000e
			public const int place_autocomplete_search_button = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int place_autocomplete_search_input = 2131296271;
			
			// aapt resource value: 0x7f090011
			public const int place_autocomplete_separator = 2131296273;
			
			// aapt resource value: 0x7f090019
			public const int placeholder = 2131296281;
			
			// aapt resource value: 0x7f090016
			public const int root = 2131296278;
			
			// aapt resource value: 0x7f09001a
			public const int root_list_button = 2131296282;
			
			// aapt resource value: 0x7f090009
			public const int satellite = 2131296265;
			
			// aapt resource value: 0x7f09001c
			public const int search = 2131296284;
			
			// aapt resource value: 0x7f090018
			public const int searchArea = 2131296280;
			
			// aapt resource value: 0x7f09000d
			public const int searchbox = 2131296269;
			
			// aapt resource value: 0x7f090001
			public const int standard = 2131296257;
			
			// aapt resource value: 0x7f09000a
			public const int terrain = 2131296266;
			
			// aapt resource value: 0x7f090021
			public const int title = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int up = 2131296290;
			
			// aapt resource value: 0x7f090002
			public const int wide = 2131296258;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int place_autocomplete_fragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int place_autocomplete_item_powered_by_google = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int place_autocomplete_item_prediction = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int place_autocomplete_progress = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SearchBox = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SearchOption = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060022
			public const int ApplicationName = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int Hello = 2131099681;
			
			// aapt resource value: 0x7f06001d
			public const int auth_google_play_services_client_facebook_display_name = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int auth_google_play_services_client_google_display_name = 2131099676;
			
			// aapt resource value: 0x7f060015
			public const int common_google_play_services_api_unavailable_text = 2131099669;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_enable_button = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_enable_text = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_enable_title = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_button = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_install_text_phone = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_text_tablet = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_install_title = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_invalid_account_text = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_invalid_account_title = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_network_error_text = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_network_error_title = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_notification_ticker = 2131099648;
			
			// aapt resource value: 0x7f060019
			public const int common_google_play_services_restricted_profile_text = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int common_google_play_services_restricted_profile_title = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int common_google_play_services_sign_in_failed_text = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int common_google_play_services_sign_in_failed_title = 2131099670;
			
			// aapt resource value: 0x7f06001e
			public const int common_google_play_services_unknown_issue = 2131099678;
			
			// aapt resource value: 0x7f060012
			public const int common_google_play_services_unsupported_text = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_unsupported_title = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_update_button = 2131099667;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_update_text = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_title = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_updating_text = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_updating_title = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_wear_update_text = 2131099658;
			
			// aapt resource value: 0x7f060014
			public const int common_open_on_phone = 2131099668;
			
			// aapt resource value: 0x7f06001a
			public const int common_signin_button_text = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int common_signin_button_text_long = 2131099675;
			
			// aapt resource value: 0x7f060020
			public const int place_autocomplete_clear_button = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int place_autocomplete_search_hint = 2131099679;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SearchBoxView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int SearchBoxView_drawableRight = 2;
			
			// aapt resource value: 1
			public const int SearchBoxView_mapsResults = 1;
			
			// aapt resource value: 0
			public const int SearchBoxView_placeholder = 0;
			
			public static int[] SignInButton = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
